### ISSUE TITLE
Make it possible to show warnings only when there are inputs, or when inputs are interacted with

### ISSUE THREAD

**Issue by cdeevfrr** [Tyler-Murphy/New-Site-Warning-browser-extension#1]
This should be configurable. It'd be a much less intrusive way of receiving some protection.

The warnings should show up until you enter text on a site to implicitly mark it as trusted, or until you explicitly mark a site as trusted.

**Comment by Tyler-Murphy** [comment]
This could also prevent weird-looking fragments of the warning on tiny embedded pages. For example, here's how some social sharing buttons look when the warning is displayed:

![image](https://user-images.githubusercontent.com/6340825/93269668-74c10180-f77d-11ea-97b2-28379cb2d409.png)

**Comment by Tyler-Murphy** [comment]
a6e0562 adds support for warnings on the `input` event. It's still not configurable. Both visits and input for new sites trigger the warning.

**Comment by Tyler-Murphy** [comment]
0402e16 adds a popup with inputs for these options. They're not hooked up yet, so they don't do anything yet. The commit message says more about what needs to happen next.

![image](https://user-images.githubusercontent.com/6340825/94616835-1c0e6000-0277-11eb-83b9-2e6d04b9c9a8.png)

**Comment by Tyler-Murphy** [comment]
How it looks:

Popup with options:

![image](https://user-images.githubusercontent.com/6340825/94744747-7f67c300-0347-11eb-8d12-cea132a3c688.png)

Warning when the `input` event fires:

![image](https://user-images.githubusercontent.com/6340825/94744786-90b0cf80-0347-11eb-86bf-d44562df83b2.png)
